// export default function Model(props) {
//   const { scene } = useGLTF(
//     'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruby/model.gltf'
//   );
//   return <primitive object={scene} {...props} />;
// }
//

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruby/model.gltf'
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Ruby.geometry} material={materials.Material} />
    </group>
  )
}

