name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16]
        include:
          - os: macos-latest
            node_version: 14
          - os: windows-latest
            node_version: 14
      fail-fast: false

    name: "Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set dependencies cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-${{ matrix.node_version }}-

      - name: Versions
        run: yarn versions

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build vitext
        run: yarn build 

      - name: Test serve
        run: yarn test-serve --runInBand

      - name: Test build
        run: yarn test-build --runInBand

  lint:
    runs-on: ubuntu-latest
    name: "Lint: node-14, ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: lint-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lint-dependencies-${{ hashFiles('yarn.lock') }}
            lint-dependencies-

      - name: Prepare
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
